### ISSUE TITLE
syntax error, unexpected keyword_end, expecting ')'

### ISSUE THREAD

**Issue by unixg33k** [isene/astropanel#1]
Getting this on lines 274, 276, 440 and 1103 using ruby 2.5.1 any idea what I might be doing wrong?

**Comment by isene** [comment]
Curious. It's certainly not you doing something wrong. It's my program, and I'm to blame.

Try installing the Curses library via gem: `gem install curses` and tell me if that changes anything.

**Comment by unixg33k** [comment]
OK - ran a gem update and gem install curses and it's installed, here is the output.  Thanks for the help on this!

```
`./astropanel.rb

./astropanel.rb:265: syntax error, unexpected ']'

...  n_o   = (p[0].upcase + p[1..]).ljust(7)

...                              ^

./astropanel.rb:274: syntax error, unexpected keyword_end, expecting ')'

    end

    ^~~

./astropanel.rb:276: syntax error, unexpected keyword_end, expecting ')'

  end

  ^~~

./astropanel.rb:440: syntax error, unexpected keyword_end, expecting ')'

./astropanel.rb:441: class definition in method body

class String # CLASS EXTENSION

                              ^

./astropanel.rb:446: class definition in method body

...rses::Window # CLASS EXTENSION

...                               ^

./astropanel.rb:1103: syntax error, unexpected end-of-input, expecting ')'

... fdm=syntax fdn=2 fcs=fold\:\ :

...                               ^`

```

**Comment by isene** [comment]
That's rather odd. 

Would it be possible for you to try it with Ruby 2.7 (which is what I'm running)?

**Comment by isene** [comment]
I may have spotted the issue (that could be specific to 2.7). Try with the latest commit.

That is,  try the latest commit on your 2.5 without upgrading to 2.7 first.

**Comment by unixg33k** [comment]
That worked!  Now I am getting:

`
./astropanel.rb

Enter Location (format like Europe/Oslo):
Traceback (most recent call last):
./astropanel.rb:61:in `<main>': uninitialized constant Readline (NameError)
Did you mean?  REQ_SCR_DLINE
`

**Comment by isene** [comment]
Cool. 

Seems that Readline is not installed. 
Try `gem install readline`

**Comment by unixg33k** [comment]
Still having the same issue - until I added this under your "begin" section:

`
begin # BASIC SETUP

  require 'net/http'

  require 'open-uri'

  require 'json'

  require 'date'

  require 'time'

  require 'curses'

  require 'readline'

  include  Curses
`

Once I put in require 'readline' it worked!  Thank you for the help again.

**Comment by isene** [comment]
Thank you for testing! Good work.

**Comment by isene** [comment]
Do tell me how you like Astropanel - you're the first official user outside of myself.
