### ISSUE TITLE
Loading user settings fails, missing newlines

### ISSUE THREAD

**Issue by maxmahlke** [isene/astropanel#2]
Nice tool!

When launching for the first time, the program prompts for location, LON/LAT ... and writes it to the `.ap.conf` file.
When launching for the second time, I got 

```
➜ astropanel ./astropanel.rb
Traceback (most recent call last):
	1: from ./astropanel.rb:59:in `<main>'
./astropanel.rb:59:in `load': /home/max/.ap.conf:2: syntax error, unexpected instance variable, expecting end-of-input (SyntaxError)
@loc = "Europe/Nice"@lat = 43.7@lon = 7.25@cloudlimit...
```

Inserting linebreaks after each variable value fixes it. I don't know ruby, so this is an issue rather than a PR.

**Comment by isene** [comment]
Yup. I missed the initial newlines. Fixed & closes this issue.

Thanks for testing :-)
