### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mthsgrc** [isene/astropanel#3]
Got this when running the astropanel.rb

.rbenv/versions/2.7.0/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- curses (LoadError)

**Comment by isene** [comment]
As per the updated [Readme](https://github.com/isene/astropanel) you need to do this: `gem install curses`

Try that and report back if it works.

**Comment by mthsgrc** [comment]
Okay. It runned, but - I don't know if I haven't inserted the right info in the initial request data - I got these:

Traceback (most recent call last):
	12: from ./astropanel.rb:1040:in `<main>'
	11: from ./astropanel.rb:1040:in `loop'
	10: from ./astropanel.rb:1046:in `block in <main>'
	 9: from ./astropanel.rb:684:in `get_planets'
	 8: from ./astropanel.rb:684:in `times'
	 7: from ./astropanel.rb:686:in `block in get_planets'
	 6: from ./astropanel.rb:686:in `new'
	 5: from ./astropanel.rb:431:in `initialize'
	 4: from ./astropanel.rb:387:in `body_calc'
	 3: from ./astropanel.rb:244:in `rts'
	 2: from ./astropanel.rb:118:in `to_hms'
	 1: from ./astropanel.rb:111:in `hms'
./astropanel.rb:111:in `to_i': NaN (FloatDomainError)

**Comment by isene** [comment]
Good that it runs. The error is interesting. Could you post your `.ap.conf` here?

When I understand why it's screaming, I can catch that type of error.

**Comment by mthsgrc** [comment]
.ap.conf?
Where is it?

**Comment by isene** [comment]
Astropanel creates the file ".ap.conf" in your home directory where it stores the values like location, latitude and windlimit. 

I just did another commit where I added better input validation when you first start the program. You might wanna give that a try and report how that worked out at your end.

... just make sure to move your .ap.conf away from your Home directory first so that the program creates a fres config file.

**Comment by mthsgrc** [comment]
I guess it works better now. 

There is an error though in the sky chart i guess:

xwininfo: error: -id requires argument

![Screenshot from 2020-12-17 20-32-02](https://user-images.githubusercontent.com/13367706/102556198-1d496f00-40a7-11eb-8f67-95b11e382bdd.png)

**Comment by isene** [comment]
That's not an error. It will show up when you hit any key. I may change that behaviour tomorrow now that I've figured out how to make the getkey non-blocking.

**Comment by isene** [comment]
Did you install w3m?

**Comment by isene** [comment]
Added this to Readme.md:

_Then there are two basic prerequisites needed: x11-utils and xdotool. On Ubuntu these would be installed via apt-get install x11-utils xdotool._

So - install x11-utils and xdotool and it should work nicely.
