### ISSUE TITLE
w3m-img is dependency; pictures display only briefly

### ISSUE THREAD

**Issue by landgrvi** [isene/astropanel#4]
Nice compilation of viewing and weather data! So far I am really enjoying this software.

I'm running Ubuntu Studio 20.04 LTS and I had to install w3m-img as a prerequisite, so maybe that should be added to the Ubuntu list in the readme.

Even after that, I still have a problem: pictures, such as the star chart, display very briefly (a few milliseconds) and then the picture area goes blank. Has anyone else reported this problem? I'm using xfce terminal but also tried xterm and gnome-terminal and didn't see the pictures at all in those.

**Comment by isene** [comment]
Good comment. Will change to w3m-img.

Try urxvt as the terminal and report back how that goes.

**Comment by landgrvi** [comment]
Thanks, urxvt works fine.
Now that I can see the star chart, though, it seems wrong. I'm at approx. 35 degrees South latitude, but Polaris is centred in the chart - almost as if I'm looking through the earth instead of at the sky.
![image](https://user-images.githubusercontent.com/76277980/102725647-2a9f7b80-437d-11eb-89fc-76b54922d2fa.png)

**Comment by landgrvi** [comment]
Oh... I just looked at the Stelvision site and they can't generate star charts below 23°N. That explains that!

**Comment by isene** [comment]
Thanks for bringing that to my attention. I have at the very least added that as a note in the README.md

**Comment by isene** [comment]
I will search harder and longer for an alternative source of start charts that covers all latitudes. If you find any,  let me know. 

Also let me know if you like the latest commits.

**Comment by landgrvi** [comment]
I see, not so easy. Maybe Planisphere (https://drifted.in/planisphere-app/app/index.xhtml, https://github.com/drifted-in/planisphere-core) would work? The constellation names seem a little odd (at least in English) but it does do a wide range of latitudes and at first glance does seem correct for my location.

**Comment by landgrvi** [comment]
Love the new planets table!

**Comment by isene** [comment]
> I see, not so easy. Maybe Planisphere (https://drifted.in/planisphere-app/app/index.xhtml, https://github.com/drifted-in/planisphere-core) would work? The constellation names seem a little odd (at least in English) but it does do a wide range of latitudes and at first glance does seem correct for my location.

Having looked at planisphere now - seems a bit too much as a dependency for astropanel - to have the user clone, build and run planisphere (which is huge). I am still searching for a good online resource...

**Comment by isene** [comment]
Until I can find an alternative starchart that cover latitude < +23, I have substituted the starchart with today's APOD image when latitude < +23.

**Comment by landgrvi** [comment]
That seems like a good workaround. I too am searching (intermittently) for a good online resource and will let you know if I find anything.
